### ISSUE TITLE
Multiple pulls at once: callback deleted.

### ISSUE THREAD

**Issue by bob-nl** [wilk/Ext.ux.data.proxy.WebSocket#24]
We use a buffered store. This store apparently loads more pages at the same time. This results in the following situation:
- Read page 1, me.callbacks["read"].operation is set to page 1.
- Read page 2, me.callbacks["read"].operation is set to page 2 .
- Data 1 received, using callback of operation of page 2 and deleting operation and callback.
- Data 2 received, no more operation/callback, get error in console because the proxy thinks it is a push and you cannot push to a buffered store.

Part of the solution is to push the operations into an array instead of setting a variable. When receiving data, look for the operation belonging to the page and only delete this one.
I am not sure how to prevent memory leaks in this situation because the operation stays in the array, even if data never comes.

I'll try to fix this.

**Comment by bob-nl** [comment]
It seems runTask is called more then once for every page.
Need to fiddle this out, may take some time.

**Comment by bob-nl** [comment]
I created a thread for this with a fiddle, feel free to help:
http://www.sencha.com/forum/showthread.php?297941-buffered-store-does-many-read-operations-at-same-time.-(fiddle-included)

**Comment by bob-nl** [comment]
It was a bug in the websocket proxy, I solved it, i create a pull request with the bugfix.

**Comment by bob-nl** [comment]
I created the pull request.
Better late then never.

**Comment by ludo6577** [comment]
Thank you for your pull request ! 
Helped me a lot, hope it will be accepted soon as web socket and buffered store are the most efficient way to use store in ExtJS

**Comment by wilk** [comment]
This project is no longer mainteined. Sorry.
